FROM postgres:16

RUN apt-get update && \
  apt-get install -y --no-install-recommends gzip && \
  rm -rf /var/lib/apt/lists/*

COPY docker/backup-entrypoint.sh /backup-entrypoint.sh
RUN chmod +x /backup-entrypoint.sh

ENTRYPOINT ["/backup-entrypoint.sh"]
